version: '3.10'

services:
  python:
    build:
      context: ./parser
    container_name: python_app
    volumes:
      - ./parser:/app
    working_dir: /app
    depends_on:
      - db
    command: python scheduler.py

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db_sctipts:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - db
    volumes:
      - ./graphana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

  django:
    build:
      context: ./django
    container_name: django_app
    volumes:
      - ./django:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  grafana_data:
