{
 "title": "PSB Dashboard",
 "time": { "from": "2024-12-21T03:41:31.113Z", "to": "2024-12-21T15:41:31.113Z" },
 "panels": [
  {
   "title": "Индекс клиентского сервиса",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH categorized_data AS (\r\n    SELECT \r\n        subcategory_type,\r\n        COUNT(*) * 1.0 / SUM(COUNT(*)) OVER () AS category_ratio,\r\n        CASE \r\n            WHEN subcategory_type = 1 THEN 0.4\r\n            WHEN subcategory_type = 2 THEN 0.2\r\n            WHEN subcategory_type = 3 THEN 0.1\r\n            WHEN subcategory_type = 4 THEN 0.3\r\n            ELSE 0\r\n        END AS weight\r\n    FROM feedback\r\n    GROUP BY subcategory_type\r\n),\r\ncategory_contributions AS (\r\n    SELECT \r\n        SUM(category_ratio * weight) AS P\r\n    FROM categorized_data\r\n),\r\noverall_stats AS (\r\n    SELECT \r\n        COUNT(*) * 1.0 AS total_feedback,\r\n        SUM(CASE WHEN feedback_type = 1 THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS S, -- Процент предложений\r\n        SUM(CASE WHEN feedback_type = 2 THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS T, -- Процент благодарностей\r\n        (SELECT P FROM category_contributions) AS P -- Процент претензий\r\n    FROM feedback\r\n)\r\nSELECT \r\n    10 * (0.3 * S + 0.3 * T + 0.4 * (1 - P)) AS IKS\r\nFROM overall_stats;\r\n"
    }
   ]
  },
  {
   "title": "Средняя оценка по отзывам",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(grade) FROM feedback"
    }
   ]
  },
  {
   "title": "Подкатегории отзывов",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Не применимо\" FROM feedback WHERE subcategory_type = 0;"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"Ошибка сотрудника\" FROM feedback WHERE subcategory_type = 1;"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"Несолгласие с тарифами\" FROM feedback WHERE subcategory_type = 2;"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"Технический сбой\" FROM feedback WHERE subcategory_type = 3;"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"Скоростью обслуживания\" FROM feedback WHERE subcategory_type = 4;"
    }
   ]
  },
  {
   "title": "Группировка по категориям",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Финансовый вопрос\" FROM feedback WHERE is_finance IS TRUE;"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"Не финансовый вопрос\" FROM feedback WHERE is_finance IS FALSE;"
    }
   ]
  },
  {
   "title": "Претензии, предложения и благодарности",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Претензия\" FROM feedback WHERE feedback_type = 1;"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"Благодарность\" FROM feedback WHERE feedback_type = 2;"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"Предложение\" FROM feedback WHERE feedback_type = 3;"
    }
   ]
  }
 ]
}